---
title: "Thema09_Log"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.width = 12,fig.height = 5)
```

Personal Access Token: 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

Research question: 

## Week 1

```{r}
library(ggplot2)
library(gridExtra)
library(tidyr)
myData <- read.csv("data/Smoker_Epigenetic_df.csv")
myData <- myData %>% drop_na()
```

```{r}
library(pander)
library(ggbiplot)
pander(head(myData))
pander(summary(myData))

columns = colnames(myData[1:4])
columns <- append(columns, "Columns 5-24")
type <- c("chr", "chr", "chr", "int", "num")
descriptions = c("GSM identifier testsubject", "Smoking status", "Gender", "Age", "Methylation Rate of CG Island")
codebook <- data.frame(columns, type, descriptions)
pander(codebook)
```

```{r}
plotfunction <- function(cg){
  ggplot(data = myData, mapping = aes_string(x = "Age", y = cg)) +
    geom_point(aes(shape = factor(Gender), color = factor(Smoking.Status))) +
    labs(caption = paste(cg, ": Scatterplot visualizing the cg values of different ages and genders.")) +
    ylab(paste("CpG Island: ", cg))
}
lapply(names(myData[c(5:24)]), plotfunction)

```

```{r}

myData.pca <- prcomp(myData[,c(5:24)], center = TRUE,scale. = FALSE)

ggbiplot(myData.pca)
```

